version: '3.3'

services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: romero13
      MYSQL_DATABASE: fazenda_db
    ports:
      - "3307:3306"

  app:
    build: ./app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: romero13
      DB_NAME: fazenda_db
    ports:
      - "5000:5000"
